name: Build & check formatting

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
        include:
          - os: ubuntu-latest
            rust: 1.63.0
          - os: ubuntu-latest
            rust: nightly
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update -y
          sudo apt-get install protobuf-compiler -y
          cargo build --release

  check-rustfmt:
    name: Check that everything is rustfmtted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # gotta run build because it has to generate proto files to check correctly
          cargo build
          cargo fmt --check
